### ISSUE TITLE
detach archive from pgmq extension

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pgmq#117]
Provide the ability to "detach" an archive table from the extension. this would prevent the archive table from being dropped when `drop extension pgmq` is run.

pseudo

```
fn detach_archive(queue_name: str)
   sql::exec( alter extension pgmq drop table pgmq.{prefix}queue_name  )
   
```

**Comment by v0idpwn** [comment]
Suggestion: allow detaching queues as well.

**Comment by v0idpwn** [comment]
This has a problem: if the schema belongs to pgmq and is dropped with the pgmq extension, we would need to move the table.

**Comment by v0idpwn** [comment]
Update: seems like the schema isn't dropped, different from the tables, etc.
