### ISSUE TITLE
pgmq-rs/ docs.rs does not render latest

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pgmq#140]
404 from  https://docs.rs/pgmq/latest/pgmq/?search=pgmq

**Comment by v0idpwn** [comment]
0.24.0 is also not rendered.

Since 0.24.0 is latest, latest wont render.

I don't know why 0.24.0 doesn't show up.

**Comment by v0idpwn** [comment]
Works now that 0.25.0 was released: https://docs.rs/pgmq/latest/pgmq/
We can a) close it b) try to release docs for 0.24.0, looks like some issue happened when running `cargo docs` for this version

**Comment by v0idpwn** [comment]
I guess we are closing it :)
