### ISSUE TITLE
Java (Spring) client

### ISSUE THREAD

**Issue by adamalexandru4** [tembo-io/pgmq#173]
Hello PGMQ Community,

I trust this message finds you well. I am pleased to share that I have developed a Java client for PGMQ, leveraging the robust Spring framework. If you are intrigued, you can explore the codebase on GitHub at https://github.com/adamalexandru4/pgmq-spring.

This Java client is designed to be ready for use, providing seamless integration with PGMQ. While it's functional, I plan to enhance and refine its features further post-holidays to ensure an even more polished user experience.

Your feedback and suggestions are highly valued. Please feel free to share your thoughts or ideas to contribute to the refinement of this client. Your insights are instrumental in the ongoing development and improvement process.

Thank you for your attention, and I look forward to collaborating with the PGMQ community to make this Java client even more robust and user-friendly.

Best regards.

**Comment by ChuckHend** [comment]
@adamalexandru4 , would you open a PR on the main readme linking to this project?
