### ISSUE TITLE
pgmq-rs can't save strings with apostrophe in them

### ISSUE THREAD

**Issue by nimrodkor** [tembo-io/pgmq#185]
Hey guys!

This is a great crate, thanks so much!

I'm trying to use it to encode a message, which is a string we get from the user, and apparently if that string includes an apostrophe it fails to save because, well, the lib doesn't escape it. Example:
let's say I want to write the following JSON message:
```json
{
     "to-do": "don't delete before you read it"
}
```

Then, when I try to save it, it turns into the following query:
```sql
INSERT INTO pgmq.q_github_events_jobs (vt, message)
VALUES ((now() + interval '0 seconds'), '{
    "to-do": "don't delete before you read it"
}'::json)
	        RETURNING msg_id;
```

Which even this preview shows is broken. Need to escape the `'` characters by duplicating them, i.e. this would work:
```sql
INSERT INTO pgmq.q_github_events_jobs (vt, message)
VALUES ((now() + interval '0 seconds'), '{
    "to-do": "don''t delete before you read it"
}'::json)
	        RETURNING msg_id;
```

Are you guys open for a contribution? Any specific pointers?

**Comment by ChuckHend** [comment]
Hey @nimrodkor, thanks for opening the issue!

Yes we are definitely taking contributions. I haven't taken a look yet, but it seems like it is probably an issue with serialization. That happens someplace near here in the Rust client.

https://github.com/tembo-io/pgmq/blob/6ea785593a740e97fe277311a0e4d6c36ca1fe20/pgmq-rs/src/lib.rs#L317-L329

**Comment by nimrodkor** [comment]
Cool @ChuckHend !

Started diving into this and I see the problem is rooted in: https://github.com/tembo-io/pgmq/blob/cf203d2c9ba5b3b3c35cbd3ffc19fe9a9406ac2a/core/src/query.rs#L165

There are 3 ways to go about this IMO:
1. My favourite - make `enqueue` return a parametrized query, and pass it into `sqlx::query_with` instead of current `sqlx::query`:
   https://github.com/tembo-io/pgmq/blob/728372173da4785aee7a3caa4f916b039c6ba0b8/pgmq-rs/src/lib.rs#L324
2. Create a parametrized query in raw sql inside the `core` crate, here:
   https://github.com/tembo-io/pgmq/blob/cf203d2c9ba5b3b3c35cbd3ffc19fe9a9406ac2a/core/src/query.rs#L172-L174
3. Smallest change - just replace all `'` with `''` - but this could go wrong really fast...

**Comment by ChuckHend** [comment]
@nimrodkor - I like the parameterized query approach the best.
