### ISSUE TITLE
v1.1.1 is missing on crates.io

### ISSUE THREAD

**Issue by jirutka** [tembo-io/pgmq#189]
[v1.1.1](https://github.com/tembo-io/pgmq/releases/tag/v1.1.1) is marked as a stable release, but it’s not available on [crates.io](https://crates.io/crates/pgmq/versions).

**Comment by ChuckHend** [comment]
The postgres extension is only published to pgxn and pgt.dev, and it's container images are published to quay.io... v1.1.1 is for the postgres extension, so you won't find it in crates.io

Only pgmq-rs and pgmq-core are published to crates.io. The python lib and the pgmq-rs crate currently follow a separate release cycle.

**Comment by jirutka** [comment]
Aha, this is quite confusing. It would be better to describe it in the readme.

Can you please release a new version of pgmq-core? I’m waiting for #171 to be available.

**Comment by ChuckHend** [comment]
Yea I agree, docs need help!

Can you bump the minor version on the Cargo.toml for pgmq-core? If not I should be able to get to it this weekend.

**Comment by jirutka** [comment]
Yeah, #191.

**Comment by ChuckHend** [comment]
@jirutka did you get everything you needed or is there another release that we need to make?

**Comment by jirutka** [comment]
Yes, I needed it for #45 and this was already merged. Thx!

**Comment by jirutka** [comment]
FYI, I’ve packaged pgmq and pg_later for Alpine Linux: [postgresql-pgmq](https://pkgs.alpinelinux.org/packages?name=postgresql-pgmq) and [postgresql-pg_later](https://pkgs.alpinelinux.org/packages?name=postgresql-pg_later).

**Comment by ChuckHend** [comment]
> FYI, I’ve packaged pgmq and pg_later for Alpine Linux: [postgresql-pgmq](https://pkgs.alpinelinux.org/packages?name=postgresql-pgmq) and [postgresql-pg_later](https://pkgs.alpinelinux.org/packages?name=postgresql-pg_later).

Awesome, thank you!
