### ISSUE TITLE
decouple message from VT in queue table

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pgmq#195]
each queue has an archive table and a queue table. Messages are stored in a column on the queue table. Reading a message from the queue is an update to the VT, which will create new tuple. When the message are small, this is not expensive. But larger the message size, the more expensive this is and ideally, we don't create new tuple for the message itself. Moving message to a separate table could be an option to avoid this, but should consider implications to read and delete performance.

**Comment by v0idpwn** [comment]
I can probably take this one :)

**Comment by ChuckHend** [comment]
Awesome, thank you @v0idpwn . I should have added that there will probably need to be some additional consideration for how this is implemented for partitioned queues. What I'm not sure is if we should partition both the VT table and the message table, or just one of them? Just need to spend some time thinking that through.

We could just implement this for non partitioned queues first and keep partitioned queues on the single-table model, and come back later and handle partitioned tables.

**Comment by ChuckHend** [comment]
Closing for now. The messages will be [toasted](https://www.postgresql.org/docs/current/storage-toast.html) automatically, so original reason for this issue is not valid imo. But, we may want to move these if we want to explore [heap only tuple](https://www.postgresql.org/docs/current/storage-hot.html#:~:text=To%20help%20reduce%20the%20overhead,including%20expression%20and%20partial%20indexes) updates to the queue table.
