### ISSUE TITLE
Any interest in a pgrx-ectomy?

### ISSUE THREAD

**Issue by olirice** [tembo-io/pgmq#199]
Hi from Supabase 👋,

I've been looking into queuing solutions and noticed pgmq depends pgrx, but that usage is mostly for SQL templating and SPI.

Curious if I missed any features that are heavily dependent on pgrx/rust or if this could potentially be plain plpgsql extension (and  [TLE](https://github.com/aws/pg_tle))?

If so, would there be interest in PRs pushing this project in that direction?

**Comment by v0idpwn** [comment]
The only problem with such a transition is that it would deter further optimization (such as what is discussed in issue #70)

**Comment by ChuckHend** [comment]
I think there could be a distribution that's compatible with TLE, basically package everything that can be moved to the SQL files and ship it. If there are shared objects that aren't compatible with TLE then those just don't ship to TLE.

**Comment by ChuckHend** [comment]
Now that #212 has merged, I think we just need to migrate the build system off `pgrx`. Probably makes sense to use [pgxs](https://www.postgresql.org/docs/current/extend-pgxs.html)to build now...

**Comment by v0idpwn** [comment]
Done in #230. Will be released soon on 1.3.2

**Comment by ChuckHend** [comment]
Closing this now. I don't think there is anything blocking pgmq from TLE and dbdev.
