### ISSUE TITLE
Missing `build-extension.sh` file, as from CONTRIB.md

### ISSUE THREAD

**Issue by wiwwo** [tembo-io/pgmq#208]
Hi there!
As specified [here](https://github.com/tembo-io/pgmq/blob/07f123ffb1943c7253483d3ecb5763f2fad4d379/CONTRIBUTING.md?plain=1#L90), there should be a `build-extension.sh` somewhere, but I cannot find it (at least in the `main` branch).

**Comment by ChuckHend** [comment]
Thank you @wiwwo for pointing that out. Seems like we forgot to update `CONTRIB.md` when we [removed that file](https://github.com/tembo-io/pgmq/commit/1d090c5e6af47caed9b852279cab02f3183813a2) from the repo.

I like the idea of building a .deb though.

**Comment by wiwwo** [comment]
Eeeehhh uuuhhhmmm...
So, just revert the change and re-publish it :-P ;-)

**Comment by ChuckHend** [comment]
> Eeeehhh uuuhhhmmm... So, just revert the change and re-publish it :-P ;-)

I wish it were that simple! That file referenced several other dependencies that no longer exist. I think it was just running the `cargo pgrx package` command in a docker container..

**Comment by ChuckHend** [comment]
How about something like this @wiwwo https://github.com/tembo-io/pgmq/pull/210?

**Comment by wiwwo** [comment]
@ChuckHend That seems to be cool, yes!!
