### ISSUE TITLE
Who is using `pgmq`?

### ISSUE THREAD

**Issue by l-7-l** [tembo-io/pgmq#228]
Are you using `pgmq`  in your project?  Showcase it here!

**Comment by ChuckHend** [comment]
We're use PGMQ at Tembo.io to buffer communications between our platform's control-plane and data-plane. control-plane sends requests to a partitioned queue. a service in the data-plane ([conductor](https://github.com/tembo-io/tembo/tree/main/conductor)) reads messages from the queue and applies them via kubernetes API. Events from the data-plane go back to another queue that is read by a service in the control-plane. We use the queue archives as audit logs. We touched on it briefly in a [blog](https://tembo.io/blog/managed-postgres-rust) earlier this year.

**Comment by ryw** [comment]
Reminded me how we had a long list of users in the Airflow README, eventually moved to seperate file https://github.com/apache/airflow/edit/main/INTHEWILD.md but just added the section to pgmq README. Please add yourself there :)

**Comment by ChuckHend** [comment]
It is a dependency in some of our other extensions too, [pg_later](https://github.com/tembo-io/pg_later) and [pg_vectorize](https://github.com/tembo-io/pg_vectorize)

**Comment by ChuckHend** [comment]
@l-7-l , do you have a project using pgmq? we have a section on the readme for this and it will be more permanent than an issue. https://github.com/tembo-io/pgmq/blob/main/pgmq-extension/README.md#who-uses-pgmq

I am going to close this issue in favor of the readme.

**Comment by l-7-l** [comment]
@ChuckHend Hi, sorry I forgot about this Issue, haha. I haven’t made up my mind yet. I did implement integration with pgmq in an e-commerce project that’s still in development, which is used for all events like orders, payments, etc. But I’m still hesitating between nats-jetstream, pgmq, and iggy. Initially, high availability isn’t a concern; it just needs to run on a single node. To be honest, I really like that pgmq can send delayed messages, whereas nats-js and iggy require additional support. The advantage of nats-js is its popularity, so I’m still in a dilemma.

Lastly, thank you for your great work.
