### ISSUE TITLE
improve management of queue archives

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pgmq#229]
pgmq.archive() deletes the message from the queue and inserts it into the queue's archive table. Messages will remain in the archive table indefinitely. Depending on volume and available storage, that can become a big problem. There's nothing preventing users from managing the queue archives themselves, but I think ideally the PGMQ API provides this for users.

In the Tembo platform, we are partitioning the archive table with pg_partman manually. Below is how we migrate an existing archive table into a partitioned table. Note: this does not migrate existing archive data to the new partitioned archive table:

Here the queue name is "data_plane_events".

```sql
BEGIN;

ALTER TABLE pgmq.a_data_plane_events RENAME TO a_data_plane_events_old;

-- DDL from existing table / same as PGMQ def but with partitioning
CREATE TABLE pgmq.a_data_plane_events (
	msg_id bigint NOT NULL,
	read_ct int4 NULL DEFAULT 0,
	enqueued_at timestamptz NULL DEFAULT now(),
	archived_at timestamptz NULL DEFAULT now(),
	vt timestamptz NULL,
	message jsonb NULL
)
PARTITION BY RANGE (archived_at);
ALTER INDEX pgmq.archived_at_idx_data_plane_events RENAME TO archived_at_idx_data_plane_events_old;
CREATE INDEX pgmqarchived_at_idx_data_plane_events ON pgmq.a_data_plane_events (archived_at);

-- initialize partman
SELECT public.create_parent(
    'pgmq.a_data_plane_events',
    'archived_at',
    'native',
    'daily'
);
-- set retention
UPDATE part_config
    SET retention = '30 days',
        retention_keep_table = false,
        retention_keep_index = false,
        infinite_time_partitions = true
    WHERE parent_table = 'pgmq.a_data_plane_events';

select public.run_maintenance();

COMMIT;
```

Once data ages out the aged partitions are just dropped and that data is lost. I think a better solution would be have the option to move the partitions to S3 instead of dropping them. We could do this by integrating with [pg_tier](https://github.com/tembo-io/pg_tier). Those aged partitions would move to S3 and remain queryable (albeit slower). This would effectively provide a "bottomless" storage for the queue archives.

**Comment by ChuckHend** [comment]
partitioning added for archives in https://github.com/tembo-io/pgmq/pull/282 

I think an integration with [pg_tier](https://github.com/tembo-io/pg_tier) would still be beneficial but will create a new issue to track that.

**Comment by riderx** [comment]
@ChuckHend personally i would love to be able to auto delete old archived row older than X, i made a function for this:
```sql
CREATE OR REPLACE FUNCTION "public"."cleanup_queue_messages"()
RETURNS "void"
LANGUAGE "plpgsql"
SECURITY DEFINER
AS $$
DECLARE
    queue_name text;
BEGIN
    -- Clean up messages older than 7 days from all queues
    FOR queue_name IN (
        SELECT name FROM pgmq.list_queues()
    ) LOOP
        -- Delete archived messages older than 7 days
        EXECUTE format('DELETE FROM pgmq.a_%I WHERE archived_at < $1', queue_name)
        USING (NOW() - INTERVAL '7 days')::timestamptz;
        
        -- Delete failed messages that have been retried more than 5 times
        EXECUTE format('DELETE FROM pgmq.q_%I WHERE read_ct > 5', queue_name);
    END LOOP;
END;
$$;
```
and i run it 
```sql
SELECT cron.schedule(
    'cleanup_queue_messages',
    '0 0 * * *',  -- Run at midnight every day
    $$SELECT cleanup_queue_messages();$$
);
```

**Comment by ChuckHend** [comment]
Hi @riderx , what you've shown definitely works and I have met people who are not using partitioned queues doing it that way.

If you're using pgmq partitioned queues then you already have this functionality. Instead of deleting records, pg_partman will drop partitions according to the retention policy. It is similar to how it is described in this [blog](https://tembo.io/blog/table-version-history#expiring-old-versions).
