### ISSUE TITLE
merge core into pgmq-rs

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pgmq#243]
`./core` previously existed to share functionality between the Postgres extension and the Rust client library and make parts of the codebase easier to test. Now that the extension does not depend on `core`, we can merge that into `pgmq-rs`.

Maybe as a part-2 of this, it would be interesting to explore how the client-only module in `pgmq-rs` might be able to use the core pl/pgsql.

**Comment by v0idpwn** [comment]
There's still some functionality in `core` that we are using on the integration tests crate

**Comment by v0idpwn** [comment]
Closed per #245 and #247
