### ISSUE TITLE
Make sure correct license is specified in metadata

### ISSUE THREAD

**Issue by brianpursley** [tembo-io/pgmq#250]
While the project license file indicates that it is licensed under the PostgreSQL license, some metadata in the project specifies a difference license is used (Apache-2.0 or MIT).

This has some effect on how pgmq is shown on sites like [crates.io](https://crates.io/crates/pgmq) which says it is licensed under Apache-2.0 for example.

Here are the places I found where I think the license needs to be updated:

* https://github.com/tembo-io/pgmq/blob/41f953c754c23d1f17e677c71ad49fe995f15d4f/pgmq-rs/README.md?plain=1#L164
* https://github.com/tembo-io/pgmq/blob/41f953c754c23d1f17e677c71ad49fe995f15d4f/pgmq-rs/Cargo.toml#L10
* https://github.com/tembo-io/pgmq/blob/41f953c754c23d1f17e677c71ad49fe995f15d4f/tembo-pgmq-python/pyproject.toml#L6
* https://github.com/tembo-io/pgmq/blob/41f953c754c23d1f17e677c71ad49fe995f15d4f/integration_test/Cargo.toml#L8

**Comment by ChuckHend** [comment]
Thanks @brianpursley - at one point (maybe still true) crates.io was throwing an error when we tried publishes those client libraries with "PostgreSQL" as the license value. I don't recall what happened with pypi.org (python lib). Maybe that all has changed though or I am just completely mistaken. I agree though, makes sense to update them all to PostgreSQL.

**Comment by brianpursley** [comment]
Ah ok.  No big deal, I was just looking at pgmq as an example for another extension I'm working on and noticed the difference so thought I would mention it
