### ISSUE TITLE
Transaction Support (Rust)

### ISSUE THREAD

**Issue by haydenflinner** [tembo-io/pgmq#257]
# Background
One of the reasons for choosing to use postgres as your message queue rather than a second system as queue is that you don't have to worry about idempotence.
That is, if all of the state for your application is in this one Postgres instance, you can do something like
```rust
let transaction = conn.begin_transaction()
let msg = pgmq.read_and_remove(transaction)
modify_pg_bizlogic_tables(msg, transaction)
transaction.end()
```
And if you fail at any point, the transaction gets rolled back, and you're all good. This is a strictly safer approach than the one presented by having a separate msg queue, which is that you modify your biz logic tables, and _then_ you `commit` the msg read in the queue (in pgmq, this would be `pgmq.archive`), and you cross your fingers that either (1) you don't crash between doing the side effects and committing the read or (2) your side effects are idempotent, it won't matter if you read the same msg again.

# Solution
If pgmq supported receiving an [ongoing transaction ](https://stackoverflow.com/a/77406271) rather than managing its own connection, this would be trivial, I could just begin the transaction, pass it in to pgmq and otherwise use it as normal, and commit the transaction when I'm done.

**Comment by ChuckHend** [comment]
Thanks @haydenflinner, just to clarify you are saying this is a limitation with the Rust client library, not the extension itself, correct? You should be able to get the desired behavior in Rust by executing SQL directly.

**Comment by haydenflinner** [comment]
Right; this could be done in plain SQL, it's just the Rust client library doesn't support this usage with the convenient API.

I may give this little refactor a shot today, found another [example](https://github.com/launchbadge/sqlx/blob/main/examples/postgres/transaction/src/main.rs). Biggest hurdle will be me figuring out how to vendor the code for my own usage 😄 I guess I could fork this repo and give Cargo the URL of my fork, but that would be a pretty slow feedback loop!

**Comment by v0idpwn** [comment]
I agree pgmq-rs should support easily wrapping statements in a transaction. In the elixir library, one can simply:

```elixir
MyApp.Repo.transaction(fn ->
  MyApp.Pgmq.send("q1", message)
  MyApp.Pgmq.send("q2", message)
end)
```

Seems hard to achieve something similar in pgmq-rs without breaking compatibility significantly :/

**Comment by v0idpwn** [comment]
I'd love to see the same in the python client, cc @ChuckHend @tavallaie

**Comment by ChuckHend** [comment]
> IMO this is one of the big selling points of pgmq over queues outside the database

Totally agree.

One way that might work could be to add a parameter to allow users to pass their transaction into the call.  I haven't tested it yet, but something like this:

```rust
    pub async fn send<T: Serialize>(
        &self,
        queue_name: &str,
        message: &T,
        cxn: Option<&mut sqlx::Transaction<'_, sqlx::Postgres>>
    ) -> Result<i64, PgmqError> {
        check_input(queue_name)?;
        let msg = serde_json::json!(&message);
        let prepared = sqlx::query!(
            "SELECT send as msg_id from pgmq.send($1::text, $2::jsonb, 0::integer);",
            queue_name,
            msg
        );
        let sent = match cxn {
            Some(tx) => prepared.fetch_one(&mut **tx).await?,
            None => prepared.fetch_one(&self.connection).await?
        };
        Ok(sent.msg_id.expect("no message id"))
    }
```

It's a breaking change, but would be an easy update for users who don't want transactions. It would be just passing in `None` as the last parameter.

**Comment by tavallaie** [comment]
I was laid off today, so I'm taking my time to add this feature :)))

**Comment by ChuckHend** [comment]
@haydenflinner , @v0idpwn, @brianpursley  -- what do you think about adding an optional parameter (for the transaction) to all the functional calls? Draft over here: https://github.com/tembo-io/pgmq/pull/273 (implemented for pgmq.send() only)

**Comment by brianpursley** [comment]
It seems reasonable, and similar to what the [sqlx transaction example](https://github.com/launchbadge/sqlx/blob/0eb2ee93650eaf10d9cadc107a88bfabfdf377a7/examples/postgres/transaction/src/main.rs#L3-L6) does.

I think what is *sort of* weird to me about the optional parameter is that it is completely independent of the pool or url I used to create `PGMQueueExt`... I *think* it has nothing to do with it. If I am using a transaction, calling `new_with_pool` is basically irrelevant, because it would use my transaction's connection instead, right?

My first instinct is to wonder why pgmq-rs needs to be aware of transactions at all. If there could be a `new_with_connection` function ("bring your own connection") that let's you give it a specific connection, and whether there is a transaction active or not would be up to the caller.  Sort of like the Elixir example that @v0idpwn posted above.

I'm new to Rust and sqlx, so I don't know if this just isn't how things are typically done, but in the C#/.NET library, it would work something like this:
```
    await using var connection = new NpgsqlConnection(connectionString);
    await connection.OpenAsync();
    var npgmq = new NpgmqClient(connection);

    await using (var tx = await connection.BeginTransactionAsync())
    {
        await npgmq.SendAsync("example_queue", msg1);
        await npgmq.SendAsync("example_queue", msg2);

        await tx.CommitAsync();
    }
```

All that being said, I think the optional parameter idea is reasonable.  I just wanted to share a few thoughts about it.

**Comment by ChuckHend** [comment]
@haydenflinner - we just added support for transactions in the Rust client ([v0.29.0](https://github.com/tembo-io/pgmq/pull/273)).

We'll get some examples added to the docs, but in the meantime there is a [test case](https://github.com/tembo-io/pgmq/blob/30ebb7dad44303f670dda5fd535de56a1d604c0b/pgmq-rs/tests/pg_ext_integration_test.rs#L373) that might be a good reference.
