### ISSUE TITLE
Consumer Retry Mechanism ?

### ISSUE THREAD

**Issue by jason810496** [tembo-io/pgmq#274]
Hi,

I am currently using `pgmq` as an alternative to RabbitMQ. 
I'm wondering if the current project supports a retry mechanism (like `x-retry-count` in RabbitMQ), or if I need to create another table to record the retry count to implement it.

> I have read the documentation about `Set the visibility timeout (VT) for a specific message`, 
> but I prefer a scenario where **the message is archived after being retried X times**.

Thank you for your help!

**Comment by ChuckHend** [comment]
Hi @jason810496, thanks for asking!

Each message has a field `read_ct` that increments every time the message is read with `pgmg.read()`

```sql
select * from pgmq.read(queue_name => 'myqueue', vt => 10, qty => 1);
```

```
 msg_id | read_ct |          enqueued_at          |              vt               |      message       
--------+---------+-------------------------------+-------------------------------+--------------------
      1 |       1 | 2024-07-01 12:39:02.198732+00 | 2024-07-01 12:39:28.176894+00 | {"hello": "world"}
```

There isn't a mechanism that will automatically move the message to another queue (like a DLQ or something). But what [some projects](https://github.com/tembo-io/tembo/blob/f49bd5548040f9494c7d26feca8e278d20503c67/conductor/src/main.rs#L164-L171) do is have their consumer check the `read_ct` value then move/archive/delete the message if it exceeds some value.

**Comment by jason810496** [comment]
Hi, @v0idpwn 
Do you have any description on how to use the project? Thanks.

**Comment by v0idpwn** [comment]
@jason810496 there's some info in the [documentation](https://hexdocs.pm/off_broadway_pgmq) and on [broadway documentation](https://hexdocs.pm/broadway)

**Comment by v0idpwn** [comment]
I'm closing this since the question was answered. If there's further questioning, please don't hesitate to comment here and we can potentially reopen.
