### ISSUE TITLE
`META.json.in` ignored via `.gitattributes`

### ISSUE THREAD

**Issue by CGenie** [tembo-io/pgmq#276]
Hello,

Any idea why the `pgmq-extension/META.json.in` file is ignored via `.gitattributes`?

https://github.com/tembo-io/pgmq/blob/main/.gitattributes#L4

This is kinda nasty because I wanted to build the extension from scratch and when I `git clone` the repository, the file is there, but when I use github's tarballs it's not there anymore. I wasted some time figuring out why is this...

**Comment by ChuckHend** [comment]
`pgmq-extension/META.json.in` is not required to build the extension. That part is only used for publishing the extension to [pgxn.org](https://pgxn.org/dist/pgmq/) Are you receiving an error related to it during the [installation steps](https://github.com/tembo-io/pgmq/blob/main/CONTRIBUTING.md#installing-pgmq)?

**Comment by v0idpwn** [comment]
Running `make` will run `make all`, which tries to make `META.json`, which requires `META.json.in`.

**Comment by v0idpwn** [comment]
I think this file is ignored to avoid shipping it in the pgxn tarball, which is built with `git archive`:
https://github.com/tembo-io/pgmq/blob/4277086f3b660d61678d9b184c3a9334fde472ce/pgmq-extension/Makefile#L26

**Comment by theory** [comment]
Yes, it's ignored for export so that it's excluded from the zip file. We can fix the GitHub tarballs by making a proper release file, [like this](https://github.com/theory/pg-semver/blob/804f9541fda7714a3317cbde7f68e6e074e980f6/.github/workflows/release.yml#L22-L37). But you can also download a properly formatted release archive [from PGXN](https://api.pgxn.org/dist/pgmq/1.3.3/pgmq-1.3.3.zip).

**Comment by theory** [comment]
And in truth, we should probably remove `META.json` from the `all:` target. I don't think there's any reason for it.

**Comment by v0idpwn** [comment]
@theory why is it needed to ignore it in gitattributes if the makefile already specifies files to be included?

**Comment by CGenie** [comment]
For the context: I wanted to create a [nix flake](https://git.sr.ht/~cgenie/postgres-pgmq-nix-flake/tree/master/item/default.nix) for pgmq for my own purposes (there are already various postgres extensions in nix). Hence, I used `fetchFromGitHub` and TIL that it uses tarballs instead of cloning the repo. And I was puzzled why doesn't it want to build in nix when it does build properly with `make` when I clone via git.

And so I used `fetchgit` from nix which just clones the repo so the `META.json.in` file was there.

**Comment by theory** [comment]
> @theory why is it needed to ignore it in gitattributes if the makefile already specifies files to be included?

It is ignored in `.gitattributes` so that it will be excluded from PGXN releases created by `git archive`. It in fact is not needed _except_ to create `META.json` for PGXN, so not important to include in any other archives. #278 should fix the issue.

**Comment by ChuckHend** [comment]
I think this was resolved in https://github.com/tembo-io/pgmq/commit/3c486310c6243c47f842c47191e125a7f3aceceb, correct?

@CGenie can you confirm that this is resolved for you?

**Comment by ChuckHend** [comment]
@CGenie - I am going to close this but let us know if this is still a problem.

**Comment by CGenie** [comment]
OK, yes, thank you!
