### ISSUE TITLE
DelaySeconds

### ISSUE THREAD

**Issue by rgarcia** [tembo-io/pgmq#283]
DelaySeconds is a useful SQS feature that allow you to send a message but only let consumers see it after a delay period. This is useful for cases where you want to requeue some work, e.g. you have a consumer that checks something every 10 minutes, so when the consumer is finished processing and deleting a message it sends a new message with a 10 minute DelaySeconds. I believe SQS limits it to a maximum of 900 seconds (15 mins).

**Comment by jason810496** [comment]
Hi,

Though I am not the official maintainer of PGMQ, here is my workaround solution for an exponential backoff retry mechanism.
The solution utilizes `read` with the `vt` option and `set_vt` with `msg_id`.

Here is an example using the [pgmq-sqlalchemy](https://github.com/jason810496/pgmq-sqlalchemy) Python client package.
> Reference: https://pgmq-sqlalchemy.readthedocs.io/en/latest/api-reference.html#pgmq_sqlalchemy.PGMQueue.set_vt 

```python
from pgmq_sqlalchemy import PGMQueue
from pgmq_sqlalchemy.schema import Message

def _exp_backoff_retry(msg: Message) -> int:
    # Exponential backoff retry
    if msg.read_ct < 5:
        return 2 ** msg.read_ct
    return 2 ** 5

def consumer_with_backoff_retry(pgmq_client: PGMQueue, queue_name: str):
    msg = pgmq_client.read(
        queue_name=queue_name,
        vt=1000,  # Set vt to 1000 seconds temporarily
    )
    if msg is None:
        return

    # Set exponential backoff retry
    pgmq_client.set_vt(
        queue_name=queue_name,
        msg_id=msg.msg_id,
        vt_offset=_exp_backoff_retry(msg)
    )
```

**Comment by ChuckHend** [comment]
Hello!

There is a `delay` parameter on send(). This makes the message unable to be read for 10 seconds after it reaches the queue. The [default value](https://github.com/tembo-io/pgmq/blob/0964892d71f5cb637c2cfefb9ade4e7799ca9cf8/pgmq-extension/sql/pgmq.sql#L246) for `delay` is zero, so if we dont set the value it just becomes immediately consumable.

```sql
select pgmq.send(
  queue_name => 'myqueue',
  msg => '{"hello": "world"}',
  delay => 10
);
```

**Comment by rgarcia** [comment]
Oh nice didn't see that! That is exactly what I am looking for. Thanks
