### ISSUE TITLE
[doc] v1.4.0 build doc outdated

### ISSUE THREAD

**Issue by elvizlai** [tembo-io/pgmq#291]
`make` returns error: `make: *** No targets specified and no makefile found.  Stop.`

**Comment by ChuckHend** [comment]
Hi @elvizlai, thank you for pointing that out. Can you try what is in https://github.com/tembo-io/pgmq/pull/292 and see if that resolves the problem?

**Comment by elvizlai** [comment]
Opps, that not work.

maybe should following ci:

https://github.com/tembo-io/pgmq/blob/main/.github/workflows/extension_ci.yml#L60-L80

**Comment by ChuckHend** [comment]
Do you still get the same error `make: *** No targets specified and no makefile found.  Stop.` when you run from within `pgmq/pgmq-extension` ?

There are a few ways to install the extension (make, trunk, pgxn) but IMO `make` is the most straight forward.

**Comment by elvizlai** [comment]
make result:
```
cp sql/pgmq.sql sql/pgmq--1.4.0.sql
sed 's/@@VERSION@@/1.4.0/g' Trunk.toml.in > Trunk.toml
```
is this correct?

**Comment by ChuckHend** [comment]
that is correct!

**Comment by elvizlai** [comment]
thanks
