### ISSUE TITLE
pgmq.purge(queue_name text) performance

### ISSUE THREAD

**Issue by olirice** [tembo-io/pgmq#298]
In `pgmq.purge(queue_name text)` it uses `delete from` with no `where` clause and then collect the row count with `GET DIAGNOSTICS`

https://github.com/tembo-io/pgmq/blob/78a766bd750b5985ac590ac384b8d294601fe544/pgmq-extension/sql/pgmq--1.4.0--1.4.1.sql#L310-L311

If the queue is large that will create a lot of IO and WAL with 1 record per deleted tuple. At scale that could contribute to exhausting IO on the primary and cause replication lag on any replicas

What do you think about swapping it out for something like
```
SELECT count(*) INTO deleted_count FROM pgmq.my_tab;
TRUNCATE pgmq.my_tab;
```
since truncate produces a single WAL record a little IO on the primary?

**Comment by ChuckHend** [comment]
Yea I think this is a good enhancement. We've also seen poor perf when queue grows very large and have used `TRUNCATE` directly on the queue table as a workaround. I think makes sense to put that in the API.

**Comment by Abiji-2020** [comment]
/attempt #298

I would like to modify the SQL to use the `TRUNCATE` and also add a feature that allows the users to choose between whether they want to truncate or delete .
