### ISSUE TITLE
pgmq.metrics for readily available messages

### ISSUE THREAD

**Issue by CGenie** [tembo-io/pgmq#301]
The `pgmq.metrics` function returns, in particular, the `queue_length` column (https://tembo-io.github.io/pgmq/api/sql/functions/#metrics) which is the total number of messages.

However, when all my messages have vt set sometime in the future, even though `queue_length > 0` I might not get any message when I issue `pgmq.read` (c.f. https://tembo-io.github.io/pgmq/api/sql/functions/#set_vt). My suggestion is to also add something like `queue_available_length` which returns the number of messages that are readily available.

**Comment by ChuckHend** [comment]
This is a good idea and I think the implementation would be fairly straight forward.

We'd need to add the `queue_availalbe_length` or `queue_length_visible` to [pgmq.metrics_result](https://github.com/tembo-io/pgmq/blob/2783a6b6d61f0f9a65a0b6cfa109d88066ce7992/pgmq-extension/sql/pgmq.sql#L309) type.

Then add something like `count(*) where vt <= now()` someplace in [pgmq.metrics()](https://github.com/tembo-io/pgmq/blob/2783a6b6d61f0f9a65a0b6cfa109d88066ce7992/pgmq-extension/sql/pgmq.sql#L319-L356)

**Comment by v0idpwn** [comment]
Done in #332, will be released in 1.5.0.
