### ISSUE TITLE
drop queue should infer queue type

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pgmq#302]
https://github.com/tembo-io/pgmq/blob/2783a6b6d61f0f9a65a0b6cfa109d88066ce7992/pgmq-extension/sql/pgmq.sql#L453 takes in a parameter designating whether the queue to drop is partitioned. When that flag is true, pgmq will handle deleting the objects/records from pg_partman as well. So if you run `pgmq.drop_queue()` on a partitioned queue without the flag, there will be some orphaned pg_partman stuff laying around.

the `pgmq.meta` table has an attribute that tracks whether table is partitioned. So on the drop_queue() call, I think we should drop the `partitioned` and replace it with a query to something like `select is_partitioned from pgmq.meta where ....`

**Comment by Saturn225** [comment]
Can I get this assigned? @ChuckHend

**Comment by ChuckHend** [comment]
implemented in https://github.com/tembo-io/pgmq/pull/319
