### ISSUE TITLE
GCP CloudSQL PostgreSQL

### ISSUE THREAD

**Issue by shinzui** [tembo-io/pgmq#31]
What's required to install it in a cloud-managed PostgreSQL server such as GCP CloudSQL?

**Comment by ChuckHend** [comment]
GCP has a process for getting extensions added to their platform: https://cloud.google.com/sql/docs/postgres/extensions#requesting-support-for-a-new-extension

Tembo Cloud will be an option soon too. One of the products is a message queue stack, which is powered by PGMQ. https://tembo.io/waitlist/

**Comment by shinzui** [comment]
Thanks. I'll open a request in GCP.
