### ISSUE TITLE
feature request: possible to have send() use a specific date time not a delay

### ISSUE THREAD

**Issue by RealZimboGuy** [tembo-io/pgmq#315]
Hi, is it possible for a new method or way to send a message when it will become available at a specific date and time. rather than trying to calculate a future date based on the duration

ie 

    select * from pgmq.send('my_queue', '{"hello": "world"}','2024-10-20 00:00:00');

**Comment by ChuckHend** [comment]
Yes this is definitely possible and we'd accept a PR for it. I would need think a bit about it, but some possible ways to do it would be to overload `pgmq.send()` so that the `delay` parameter accepts either an integer or a timestamp type. OR, perhaps we add a new function `pgmq.send_at()`.

**Comment by RealZimboGuy** [comment]
I can try dive into the change and see where i end up. Will be quite a bit of learning if i have to go much into the rust side of the plugin.

**Comment by ChuckHend** [comment]
The postgres extension itself is all pl/pgsql now. You can add/modify the code in [pgmq.sql](https://github.com/tembo-io/pgmq/blob/e2740d0da8e663618feb19e9c6f6653de861fe14/pgmq-extension/sql/pgmq.sql#L264), then follow the install steps in the [contributing guide](https://github.com/tembo-io/pgmq/blob/main/CONTRIBUTING.md#installing-postgres) to install the new code locally as you develop it.

**Comment by Saturn225** [comment]
Can I get this assigned? I will push changes in the PR by EOD

cc: @ChuckHend

**Comment by Neptune650** [comment]
@ChuckHend Hey there, I don't think I was rewarded... Could you please check it.

**Comment by ChuckHend** [comment]
> @ChuckHend Hey there, I don't think I was rewarded... Could you please check it.

Sorry for delay @Neptune650. Reward should be distributed now.

**Comment by Neptune650** [comment]
> > @ChuckHend Hey there, I don't think I was rewarded... Could you please check it.
> 
> Sorry for delay @Neptune650. Reward should be distributed now.

@ChuckHend Thanks, I appreciate it.
