### ISSUE TITLE
Building the pgmq extension on windows

### ISSUE THREAD

**Issue by mercurial-moon** [tembo-io/pgmq#316]
Hi,
is there any guide to get the pgmq postgres extension build on windows. 
I see that there is a `pgmq-extension` directory and there are several `.sql` files in that and a `pgmq.control` file but no `.dll` that I could use on windows.
I see that there a `MakeFile` but not sure if that would build on windows, I guess you need a `MakeFile.win` to get it build on windows.

**Comment by ChuckHend** [comment]
@mercurial-moon - there are no shared objects in the postgres extension. And we added a guide for [windows installation](https://github.com/tembo-io/pgmq/blob/main/CONTRIBUTING.md#windows-installation). Can you take a look and reopen this issue if it does not work for you?
