### ISSUE TITLE
pgmq_list_queues errors if no queues were created

### ISSUE THREAD

**Issue by v0idpwn** [tembo-io/pgmq#32]
**Extension version**: 0.10
**Postgres version**: 15.3 (I'm running your docker image)

### Current behaviour
Running `select * from pgmq_list_queues()` throws an error if no queues were created yet:
```
SQL Error [42P01]: ERROR: relation "public.pgmq_meta" does not exist
```

### Expected behaviour
An empty result set.

**Comment by v0idpwn** [comment]
This happens because some setup necessary setup is conditionally performed on `create_queue`, and `list_queues` doesn't check if such setup was performed, nor runs it.

**Comment by ChuckHend** [comment]
I think we can solve this my moving it into the extension's sql, which will have that create table statement ran on `create extension pgmq`

**Comment by v0idpwn** [comment]
Seems like a good approach. I can try sending a PR with this fix.

**Comment by ChuckHend** [comment]
> Seems like a good approach. I can try sending a PR with this fix.

Awesome! pgrx has a macro to help with that. Macro can [reference a .sql](https://github.com/tembo-io/pg_vectorize/blob/ba52bb9209b3bbe33c1d63f9acde3f4f72f08874/src/lib.rs#L16) or the sql can [live in Rust directly ](https://github.com/pgcentralfoundation/pgrx/blob/develop/pgrx-examples/custom_sql/src/lib.rs#L50-L57)

Let me know if you run into problems. There might be some unwinding needed of the `create_*()` stuff in `./core`

**Comment by v0idpwn** [comment]
I have written this:  https://github.com/tembo-io/pgmq/commit/0c2b8829dc57b59054b95e332b41b7d2d9a7decd
But it has a few problems:
- Schema and table name are hardcoded
- I didn't build it locally yet

**Comment by ChuckHend** [comment]
The project is hard coded to the public schema at the moment, but we want to change that eventually to be set whatever comes on the `create extension` statement. e.g. `create extension pgmq schema my_schema` would put that in `my_schema`. So hardcoding it now is no different than how things are currently set up.

**Comment by ChuckHend** [comment]
> 

pgrx.

**Comment by ChuckHend** [comment]
Fixed in https://github.com/tembo-io/pgmq/pull/66


```sql
pgmq=# create extension pgmq;
CREATE EXTENSION
pgmq=# \dt
            List of relations
 Schema |   Name    | Type  |   Owner    
--------+-----------+-------+------------
 public | pgmq_meta | table | adamhendel
(1 row)

pgmq=# select * from pgmq_meta;
 queue_name | created_at 
------------+------------
(0 rows)

pgmq=# select pgmq_list_queues();
 pgmq_list_queues 
------------------
(0 rows)
```
