### ISSUE TITLE
pgmq_create doesn't validate queue names

### ISSUE THREAD

**Issue by v0idpwn** [tembo-io/pgmq#33]
**Extension version**: 0.10
**Postgres version**: 15.3 (I'm running your docker image)

### Current behaviour
Some characters that aren't allowed cause error 22000: 
```
>select * from pgmq_create('hello-world');
SQL Error [22000]
```
Very long names get truncated and cause issues:
```
>select * from pgmq_create('veryloooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooooongstring'); 
SQL Error [42703]: column "deleted_at" does not exist
```
### Expected behaviour
If the name is valid, queue is created normally. If it isn't, error early. 

This should also probably be documented somewhere.

**Comment by ChuckHend** [comment]
Nice find! Table name length limitation is 63 characters in postgres, so we probably just add that check in here: https://github.com/tembo-io/pgmq/blob/aaaf47e899dce52034f01503c60425bcc666e1d1/core/src/query.rs#L303

Thoughts?

**Comment by vrmiguel** [comment]
I feel like we already handle `pgmq_create('hello-world')` but need some way of providing a better error message to the user

**Comment by ChuckHend** [comment]
@vrmiguel - did #37 close this, or was there something we wanted to do before we marked this one done?
