### ISSUE TITLE
pgmq.read_with_poll consumes 100% for each invocation with short polling interval

### ISSUE THREAD

**Issue by szobov** [tembo-io/pgmq#342]
Hello, dear maintainers,

When `pgmq.read_with_poll` is called with a short polling interval (5 ms) directly from the psql console or client libraries, it starts consuming 100% CPU for each connection.
To reproduce this behaviour, you can either run in psql console:
```
select pgmq.read_with_poll("myqueue", 10, 10, 30, 5);
```
Or in Python:
```
queue.read_with_poll("myqueue", max_poll_seconds=30, poll_interval_ms=5, qty=1)
```
And check `top` or `htop` output.

The version of pgmq I use is `tembo/pg17-pgmq:latest`.

It was reported initially in the slack [channel](tembocommunity.slack.com/archives/C05LFV8VDV4/p1731588941553199).

Let me know if I can help with the fix.
Thanks.

Best wishes,
Sergei

**Comment by v0idpwn** [comment]
Fixed in #343, thanks for the report!
