### ISSUE TITLE
refactor SQL API

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pgmq#52]
when the pgmq objects are scoped to the [pgmq schema](https://github.com/tembo-io/pgmq/issues/51), we can simplify the naming of the main functions. For example,

current: `pgmq_send()`
1.0: `pgmq.send()`

This can be implemented as soon as the schema updates are complete. It should also be implemented as a non-breaking change. i.e. do not delete `pgmq_send()` rather add `pgmq.send()`. We can drop `pgmq_send()` on the 1.0 release since it is a major breaking change.

**Comment by v0idpwn** [comment]
This will be closed by #115. Docs will be pending.
