### ISSUE TITLE
Transaction support?

### ISSUE THREAD

**Issue by darky** [tembo-io/pgmq#54]
```sql
BEGIN;

SELECT * from pgmq_send('my_queue', '{"foo": "bar1"}');

ROLLBACK;
```

Will message exists in queue in this case? ☝️

**Comment by ChuckHend** [comment]
This is definitely something we want to support and have well tested though. Thank you for bringing it up @darky!

**Comment by v0idpwn** [comment]
Closing this in favor of #130. If you think additional tests should be made, we can discuss that
