### ISSUE TITLE
send_with_delay()

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pgmq#85]
It's implement in the client-only sdk. also implement it the extension
https://github.com/tembo-io/pgmq/blob/0c52bc6a8c405f0ed65a753d7bacecde0dcbac99/pgmq-rs/src/lib.rs#L371

**Comment by v0idpwn** [comment]
Should it be a third parameter to `send` as it is with `send_batch`?

**Comment by ChuckHend** [comment]
> Should it be a third, optional, parameter to `send` as it is with `send_batch`?

Yes I agree. I think that's the cleanest and simplest solution.
