### ISSUE TITLE
Return value of the batch values of pgmq_archive and pgmq_delete

### ISSUE THREAD

**Issue by craigpastro** [tembo-io/pgmq#89]
At the moment it seems like pgmq_archive(_batch) always returns `t` even if there was nothing to archive.
```
postgres=# select * from pgmq_archive('my_queue', array[3]);
 pgmq_archive
--------------
 t
(1 row)

postgres=# select * from pgmq_archive('my_queue', array[3]);
 pgmq_archive
--------------
 t
(1 row)
```
What do you think about returning the actual number of archived messages? Or rows of boolean indicating which were deleted... I am not sure how useful this would be though.

**Comment by craigpastro** [comment]
I'm happy to attempt a PR if this is something that you think would be useful!

**Comment by ChuckHend** [comment]
I think this is a good idea. Row of booleans would be consistent with the single message archive. Its a bug that it returns T even though no messages were archived.

**Comment by craigpastro** [comment]
Cool. I'll give it a try. It's been a hot minute since I've written any Rust so we'll see 🙃

**Comment by ChuckHend** [comment]
There will also be some pgrx stuff you'll have to work with, which could be fun :)

Returning data as a postgres row takes some extra steps. It would need to be returned as a "TableIterator", I think. Here's an example in our project: https://github.com/tembo-io/pgmq/blob/759af076b84c032c60e889f3bcef6fb1764eca43/src/api.rs#L78

And there's some more examples in the pgrx repo too 
https://github.com/pgcentralfoundation/pgrx/blob/27a0d162ed938b1ebd7ba12be807877abac7998c/pgrx-examples/spi_srf/src/lib.rs#L38-L48

**Comment by craigpastro** [comment]
Thanks @ChuckHend! That looks like a great place to start.
