### ISSUE TITLE
add 'partitioned' attribute to pgmq_meta

### ISSUE THREAD

**Issue by ChuckHend** [tembo-io/pgmq#91]
pgmq_meta should have an attribute that tracks whether the queue is partitioned or not. This will be useful when dropping a queue, so we can also cleanup relevant entries in pg_partman. But also for general observability into existing queue.

Does not necessarily need to explicitly be "partitioned" as the attribute name, but some attribute that lets us know how the type of queue when inspecting pgmq_meta. Right now, there are just two types; partitioned and non-partitioned. In the future, there could be several types of partitioning.

**Comment by craigpastro** [comment]
👋 Mind if I give this one a shot too? For the moment, as you said, there are just two types so we could go with
```
CREATE TABLE public.pgmq_meta (
    queue_name VARCHAR UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    partitioned BOOLEAN DEFAULT false NOT NULL
);
```
But if you think there are going to be more types soon we could try something like
```
CREATE TABLE public.pgmq_meta (
    queue_name VARCHAR UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    type TEXT NOT NULL check(type in ('non-partitioned','partitioned'))
);
```
WDYT?

**Comment by ChuckHend** [comment]
> CREATE TABLE public.pgmq_meta (
    queue_name VARCHAR UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT now() NOT NULL,
    type TEXT NOT NULL check(type in ('non-partitioned','partitioned'))
);

I like this. There's going to be multiple partition types for sure.

@v0idpwn - any thoughts?

**Comment by v0idpwn** [comment]
My problem with this approach is that, okay, "partitioned" and "non-partitioned" are mutually excludent, but this isn't necessarily true for all "queue types" including future ones, right?

**Comment by ChuckHend** [comment]
> On this sense, I think going for a simpler "is_partitioned" boolean column is enough. Or a "partition type" column which uses an enum.

I like this. Let's start with a simple boolean flag. We can implement something more exhaustive when its clearer exactly what we'll need. This definitely fits the current needs though will be long-lived.
